version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - /config.yaml:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host